import mongoose from 'mongoose';
import { ok,fail } from '../utils/api.js';
export function makeCrud(Model,{populate=[]}= {}){
 return {
  list:async(req,res)=>{const page=Math.max(Number(req.query.page)||1,1),limit=Math.min(Math.max(Number(req.query.limit)||20,1),100),filter={}; const reserved=new Set(['page','limit','search','sort','from','to']); for(const [k,v] of Object.entries(req.query)){if(!reserved.has(k)&&v!==''&&v!==undefined)filter[k]=v;} if(req.query.search){const rx=new RegExp(String(req.query.search).replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'); filter.$or=['name','title','email','studentId','employeeId','bookId','memberId','receiptNo','transactionId'].map(k=>({[k]:rx}));} if(req.query.from||req.query.to){filter.date={};if(req.query.from)filter.date.$gte=new Date(req.query.from);if(req.query.to)filter.date.$lte=new Date(`${req.query.to}T23:59:59.999Z`);} const sort=req.query.sort&&/^[a-zA-Z0-9_,-]+$/.test(req.query.sort)?Object.fromEntries(String(req.query.sort).split(',').map(x=>{const [k,d]=x.split(':');return [k,d==='desc'?-1:1]})):{createdAt:-1}; const [items,total]=await Promise.all([Model.find(filter).sort(sort).skip((page-1)*limit).limit(limit).populate(populate),Model.countDocuments(filter)]); return ok(res,items,'Records fetched',200,{pagination:{page,limit,total,pages:Math.ceil(total/limit)}});},
  get:async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return fail(res,'Invalid identifier',400);const doc=await Model.findById(req.params.id).populate(populate);if(!doc)return fail(res,'Record not found',404);return ok(res,doc);},
  create:async(req,res)=>{const doc=await Model.create(req.body);return ok(res,doc,'Record created successfully',201);},
  update:async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return fail(res,'Invalid identifier',400);const doc=await Model.findByIdAndUpdate(req.params.id,req.body,{new:true,runValidators:true}).populate(populate);if(!doc)return fail(res,'Record not found',404);return ok(res,doc,'Record updated successfully');},
  patch:async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return fail(res,'Invalid identifier',400);const doc=await Model.findByIdAndUpdate(req.params.id,{$set:req.body},{new:true,runValidators:true}).populate(populate);if(!doc)return fail(res,'Record not found',404);return ok(res,doc,'Record patched successfully');},
  remove:async(req,res)=>{if(!mongoose.isValidObjectId(req.params.id))return fail(res,'Invalid identifier',400);const doc=await Model.findByIdAndDelete(req.params.id);if(!doc)return fail(res,'Record not found',404);return ok(res,doc,'Record deleted successfully');}
 };
}
